### ISSUE TITLE
Plugin doesn’t work

### ISSUE THREAD

**Issue by Fyrlex** [PYRRH4/PyrParticles#1]
### Issue description
Error preventing plugin being enabled

### Versions
Spigot : 
1.7.10
PyrCore : 
3.2.10
PyrParticles : 
4.0.0
### Log file
[12:44:34] [Server thread/INFO]: Starting minecraft server version 1.7.10
[12:44:34] [Server thread/INFO]: Loading properties
[12:44:34] [Server thread/INFO]: Default game type: ADVENTURE
[12:44:34] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[12:44:35] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:44:35] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:44:35] [Server thread/INFO]: Debug logging is disabled
[12:44:35] [Server thread/INFO]: Generating keypair
[12:44:35] [Server thread/INFO]: Starting Minecraft server on *:41252
[12:44:35] [Server thread/WARN]: Plugin `Ultimate_Freeze v0.1' uses the space-character (0x20) in its name `Ultimate Freeze' - this is discouraged
[12:44:35] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[12:44:35] [Server thread/INFO]: [eZProtector] Your server is running version v1_7_R4
[12:44:36] [Server thread/INFO]: [AutoIgnite] Loading AutoIgnite v1.0
[12:44:36] [Server thread/INFO]: [SimpleLobbyHubCommands] Loading SimpleLobbyHubCommands v1.0
[12:44:36] [Server thread/INFO]: [ColoredSigns] Loading ColoredSigns v1.0.0
[12:44:36] [Server thread/INFO]: [Ultimate_Freeze] Loading Ultimate_Freeze v0.1
[12:44:36] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.8.5
[12:44:36] [Server thread/INFO]: [PacketListenerApi] Loading PacketListenerApi v3.6.0-SNAPSHOT
[12:44:36] [Server thread/INFO]: [ReflectionHelper] Version is v1_7_R4 (10704)
[12:44:36] [Server thread/INFO]: [PacketListenerAPI] Using NMUChannel
[12:44:36] [Server thread/INFO]: Injected custom channel handlers.
[12:44:36] [Server thread/INFO]: [SimpleFlyPlugin] Loading SimpleFlyPlugin v1.14
[12:44:36] [Server thread/INFO]: [AdvancedBan] Loading AdvancedBan v2.1.4-RELEASE
[12:44:36] [Server thread/INFO]: [RetainedPvP] Loading RetainedPvP v1.0
[12:44:36] [Server thread/INFO]: [NametagEdit] Loading NametagEdit v4.1.4
[12:44:36] [Server thread/INFO]: [BuycraftX] Loading BuycraftX v10.6.0
[12:44:36] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.7.0
[12:44:36] [Server thread/INFO]: [eZProtector] Loading eZProtector v4.1.5
[12:44:36] [Server thread/INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v18.01.20-ca906cc-986-18.4.1
[12:44:36] [Server thread/INFO]: [LobbyFireworks] Loading LobbyFireworks v1.1
[12:44:36] [Server thread/INFO]: [ThrowableTnt] Loading ThrowableTnt v1.2
[12:44:36] [Server thread/INFO]: [Soup] Loading Soup v1.0
[12:44:36] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.22.10
[12:44:36] [Server thread/INFO]: [Survey] Loading Survey v1.0
[12:44:36] [Server thread/INFO]: [ShopWarp] Loading ShopWarp v1.0
[12:44:36] [Server thread/INFO]: [EasyChatPrefix] Loading EasyChatPrefix v1.3.0
[12:44:36] [Server thread/INFO]: [Vault] Loading Vault v1.6.1
[12:44:36] [Server thread/INFO]: [ServerListPlus] Loading ServerListPlus v3.4.8
[12:44:36] [Server thread/INFO]: [PyrCore] Loading PyrCore v3.2.10
[12:44:36] [Server thread/INFO]: [ProPractice] Loading ProPractice v6.5
[12:44:36] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.7;dd00bb1
[12:44:36] [Server thread/INFO]: [Essentials] Loading Essentials v2.0.1-b488
[12:44:36] [Server thread/INFO]: [AutoAnnouncer] Loading AutoAnnouncer v1.7-03.23
[12:44:36] [Server thread/INFO]: [Statscraft] Loading Statscraft v1.2.0
[12:44:36] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.1
[12:44:36] [Server thread/INFO]: [PyrParticles] Loading PyrParticles v4.0.0
[12:44:36] [Server thread/INFO]: [MaintenanceMode] Loading MaintenanceMode v2.2
[12:44:36] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v3.7.0
[12:44:36] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[12:44:36] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v18.01.20-ca906cc-986-18.4.1
[12:44:37] [Server thread/INFO]: ====== USE PAPER ======
[12:44:37] [Server thread/INFO]: DOWNLOAD: https://ci.destroystokyo.com/job/PaperSpigot/
[12:44:37] [Server thread/INFO]: GUIDE: https://www.spigotmc.org/threads/21726/
[12:44:37] [Server thread/INFO]:  - This is only a recommendation
[12:44:37] [Server thread/INFO]: ==============================
[12:44:37] [Server thread/INFO]: [Vault] Enabling Vault v1.6.1
[12:44:37] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[12:44:37] [Server thread/INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[12:44:37] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[12:44:37] [Server thread/INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[12:44:37] [Server thread/INFO]: [Vault] Plugin enabled (41ms)
[12:44:37] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[12:44:37] [Server thread/INFO]: Preparing level "Hub"
[12:44:37] [Server thread/INFO]: -------- World Settings For [Hub] --------
[12:44:37] [Server thread/INFO]: Mob Spawn Range: 100
[12:44:37] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:44:37] [Server thread/INFO]: Anti X-Ray: true
[12:44:37] [Server thread/INFO]: 	Engine Mode: 1
[12:44:37] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[12:44:37] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[12:44:37] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:44:37] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:44:37] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:44:37] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:44:37] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:44:37] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:44:37] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:44:37] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[12:44:37] [Server thread/INFO]: Entity Tracking Range: Pl 100 / An 100 / Mo 100 / Mi 100 / Other 100
[12:44:37] [Server thread/INFO]: Alternative Hopper Ticking: false
[12:44:37] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:44:37] [Server thread/INFO]: Random Lighting Updates: false
[12:44:37] [Server thread/INFO]: Structure Info Saving: true
[12:44:37] [Server thread/INFO]: Sending up to 10 chunks per packet
[12:44:37] [Server thread/INFO]: Max Entity Collisions: 8
[12:44:37] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[12:44:37] [Server thread/INFO]: Max TNT Explosions: 100
[12:44:37] [Server thread/INFO]: View Distance: 32
[12:44:37] [Server thread/INFO]: Chunks to Grow per Tick: 650
[12:44:37] [Server thread/INFO]: Clear tick list: false
[12:44:37] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:44:37] [Server thread/INFO]: Item Despawn Rate: 1200
[12:44:37] [Server thread/INFO]: Item Merge Radius: 2.5
[12:44:37] [Server thread/INFO]: Arrow Despawn Rate: 6000
[12:44:37] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:44:37] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:44:37] [Server thread/INFO]: Preparing start region for level 0 (Seed: 1315458123718687584)
[12:44:38] [Server thread/INFO]: [AutoIgnite] Enabling AutoIgnite v1.0
[12:44:38] [Server thread/INFO]: [SimpleLobbyHubCommands] Enabling SimpleLobbyHubCommands v1.0
[12:44:38] [Server thread/INFO]: [SimpleLobbyHubCommands] SimpleLobbyHubCommands has been enabled (V. 1.0)
[12:44:38] [Server thread/INFO]: [ColoredSigns] Enabling ColoredSigns v1.0.0
[12:44:38] [Server thread/INFO]: ColoredSigns is now enabled.
[12:44:38] [Server thread/INFO]: [Ultimate_Freeze] Enabling Ultimate_Freeze v0.1
[12:44:38] [Server thread/INFO]: [Ultimate_Freeze] Ultimate Freeze V0.1 loading commands...
[12:44:38] [Server thread/INFO]: [Ultimate_Freeze] Ultimate Freeze V0.1 loading config...
[12:44:38] [Server thread/INFO]: [Ultimate_Freeze] Ultimate Freeze V0.1 loading events...
[12:44:38] [Server thread/INFO]: [Ultimate_Freeze] Ultimate Freeze V0.1 started!
[12:44:38] [Server thread/INFO]: [Ultimate_Freeze] Ultimate Freeze V0.1 checking for updates...
[12:44:38] [Server thread/INFO]: ------------------------
[12:44:38] [Server thread/INFO]: Ultimate Freeze is up to date!
[12:44:38] [Server thread/INFO]: ------------------------
[12:44:38] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.8.5
[12:44:38] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[12:44:38] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: worldguard
[12:44:39] [Server thread/INFO]: [PlaceholderAPI] NMS placeholders such as %player_ping% have been enabled!
[12:44:39] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player
[12:44:39] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: vault
[12:44:39] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server
[12:44:39] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: parkour
[12:44:39] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[12:44:39] [Server thread/INFO]: [PacketListenerApi] Enabling PacketListenerApi v3.6.0-SNAPSHOT
[12:44:39] [Server thread/INFO]: Adding channels for online players...
[12:44:39] [Server thread/INFO]: [SimpleFlyPlugin] Enabling SimpleFlyPlugin v1.14
[12:44:39] [Server thread/INFO]: [SimpleFlyPlugin] SimpleFlyPlugin has been enabled!
[12:44:39] [Server thread/INFO]: [AdvancedBan] Enabling AdvancedBan v2.1.4-RELEASE
[12:44:39] [Server thread/INFO]: 
 
[]=====[Enabling AdvancedBan]=====[]
| Information:
|   Name: AdvancedBan
|   Developer: Leoko
|   Version: 2.1.4-RELEASE
|   Storage: HSQLDB (local)
| Support:
|   Skype: Leoko33
|   Mail: Leoko4433@gmail.com
| Update:
|   There is a new version available! [2.1.3-RELEASE]
[]================================[]
 
[12:44:39] [Server thread/INFO]: [RetainedPvP] Enabling RetainedPvP v1.0
[12:44:39] [Server thread/INFO]: [RetainedPvP] RetainedPvP has been enabled (V. 1.0)
[12:44:39] [Server thread/INFO]: [NametagEdit] Enabling NametagEdit v4.1.4
[12:44:39] [Server thread/INFO]: [NametagEdit] Found PermissionsEx! Hooking in.
[12:44:39] [Server thread/INFO]: [BuycraftX] Enabling BuycraftX v10.6.0
[12:44:39] [Server thread/INFO]: [BuycraftX] Validating your server key...
[12:44:40] [Server thread/INFO]: [BuycraftX] Fetching all server packages...
[12:44:40] [Server thread/INFO]: [BuycraftX] Updating coupon list...
[12:44:40] [Server thread/INFO]: [eZProtector] Enabling eZProtector v4.1.5
[12:44:40] [Server thread/INFO]: [eZProtector] Reloading config...
[12:44:40] [Server thread/INFO]: [eZProtector] Your server version is compatible with eZProtector.
[12:44:40] [Server thread/INFO]: [eZProtector] The plugin has enabled successfully. Version: 4.1.5
[12:44:40] [Server thread/INFO]: [LobbyFireworks] Enabling LobbyFireworks v1.1
[12:44:40] [Server thread/INFO]: [LobbyFireworks] Hey There! LobbyFireworks has been enabled!
[12:44:40] [Server thread/INFO]: [ThrowableTnt] Enabling ThrowableTnt v1.2
[12:44:41] [Server thread/INFO]: ThrowableTnt » Config loaded!
[12:44:41] [Server thread/INFO]: [Soup] Enabling Soup v1.0
[12:44:41] [Server thread/INFO]: [Soup] |----------------------------------------|
[12:44:41] [Server thread/INFO]: [Soup] | Soup has successfully been enabled!    |
[12:44:41] [Server thread/INFO]: [Soup] |----------------------------------------|
[12:44:41] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.22.10
[12:44:41] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[12:44:41] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[12:44:41] [Server thread/INFO]: [Vault][Permission] PermissionsEx hooked.
[12:44:41] [Server thread/INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[12:44:41] [Server thread/INFO]: [Survey] Enabling Survey v1.0
[12:44:41] [Server thread/INFO]: [Survey] Survey has been enabled (V. 1.0)
[12:44:41] [Server thread/INFO]: [ShopWarp] Enabling ShopWarp v1.0
[12:44:41] [Server thread/INFO]: [ShopWarp] ShopWarp has been enabled (V. 1.0)
[12:44:41] [Server thread/INFO]: [EasyChatPrefix] Enabling EasyChatPrefix v1.3.0
[12:44:41] [Server thread/INFO]: [EasyPrefix] Plugin by Christian34
[12:44:41] [Server thread/INFO]: [ServerListPlus] Enabling ServerListPlus v3.4.8
[12:44:41] [Server thread/INFO]: [ServerListPlus] [Core] Reloading configuration...
[12:44:41] [Server thread/INFO]: [ServerListPlus] [Core] Loaded configuration: ServerStatusConf
[12:44:41] [Server thread/INFO]: [ServerListPlus] [Core] Loaded configuration: PluginConf
[12:44:41] [Server thread/INFO]: [ServerListPlus] [Core] Reloading saved player identities...
[12:44:41] [Server thread/INFO]: [ServerListPlus] Successfully loaded!
[12:44:41] [Server thread/INFO]: [ServerListPlus] ServerListPlus v3.4.8 enabled.
[12:44:41] [Server thread/INFO]: [PyrCore] Enabling PyrCore v3.2.10
[12:44:41] [Server thread/INFO]: [PyrCore] INFO: Allowing AutoUpdate : true
[12:44:41] [Server thread/INFO]: [PyrCore] INFO: Using mysql : no
[12:44:41] [Server thread/INFO]: [PyrCore] SUCCESS: PyrCore v3.2.10 has been enabled !
[12:44:41] [Server thread/INFO]: [ProPractice] Enabling ProPractice v6.5
[12:44:41] [Thread-13/WARN]: [PermissionsEx] An update to PermissionsEx version 1.23.4 is available to download from http://dev.bukkit.org/bukkit-plugins/permissionsex/. Please review the changes and update as soon as possible!
[12:44:41] [Server thread/INFO]: [ProPractice] Initializing...
[12:44:41] [Server thread/INFO]: [ProPractice] Initializing ConfigManager...
[12:44:41] [Server thread/INFO]: [ProPractice] Initializing ArenaManager...
[12:44:41] [Server thread/INFO]: -------- World Settings For [ProPractice-Arenas] --------
[12:44:41] [Server thread/INFO]: Mob Spawn Range: 100
[12:44:41] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[12:44:41] [Server thread/INFO]: Anti X-Ray: true
[12:44:41] [Server thread/INFO]: 	Engine Mode: 1
[12:44:41] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[12:44:41] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[12:44:41] [Server thread/INFO]: Cactus Growth Modifier: 100%
[12:44:41] [Server thread/INFO]: Cane Growth Modifier: 100%
[12:44:41] [Server thread/INFO]: Melon Growth Modifier: 100%
[12:44:41] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[12:44:41] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[12:44:41] [Server thread/INFO]: Sapling Growth Modifier: 100%
[12:44:41] [Server thread/INFO]: Wheat Growth Modifier: 100%
[12:44:41] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[12:44:41] [Server thread/INFO]: Entity Tracking Range: Pl 100 / An 100 / Mo 100 / Mi 100 / Other 100
[12:44:41] [Server thread/INFO]: Alternative Hopper Ticking: false
[12:44:41] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[12:44:41] [Server thread/INFO]: Random Lighting Updates: false
[12:44:41] [Server thread/INFO]: Structure Info Saving: true
[12:44:41] [Server thread/INFO]: Sending up to 10 chunks per packet
[12:44:41] [Server thread/INFO]: Max Entity Collisions: 8
[12:44:41] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[12:44:41] [Server thread/INFO]: Max TNT Explosions: 100
[12:44:41] [Server thread/INFO]: View Distance: 32
[12:44:41] [Server thread/INFO]: Chunks to Grow per Tick: 650
[12:44:41] [Server thread/INFO]: Clear tick list: false
[12:44:41] [Server thread/INFO]: Experience Merge Radius: 3.0
[12:44:41] [Server thread/INFO]: Item Despawn Rate: 1200
[12:44:41] [Server thread/INFO]: Item Merge Radius: 2.5
[12:44:41] [Server thread/INFO]: Arrow Despawn Rate: 6000
[12:44:41] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[12:44:41] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[12:44:41] [Server thread/INFO]: Preparing start region for level 1 (Seed: 4402537033139314371)
[12:44:42] [Server thread/INFO]: [ProPractice] Initializing LadderManager...
[12:44:42] [Server thread/INFO]: [ProPractice] Initializing MatchManager...
[12:44:42] [Server thread/INFO]: [ProPractice] Initializing QueueManager...
[12:44:42] [Server thread/INFO]: [ProPractice] Initializing EditManager...
[12:44:42] [Server thread/INFO]: [ProPractice] Initializing ScoreboardManager...
[12:44:42] [Server thread/INFO]: [ProPractice] Initializing PartyManager...
[12:44:42] [Server thread/INFO]: [ProPractice] Initializing CommandManager...
[12:44:42] [Server thread/INFO]: [ProPractice] Registering Events...
[12:44:42] [Server thread/INFO]: [ProPractice] Initialized! Took 845 milliseconds.
[12:44:42] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.7;dd00bb1
[12:44:42] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[12:44:42] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.CraftBukkit_v1_7_R4 as the Bukkit adapter
[12:44:42] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b488
[12:44:42] [Server thread/INFO]: [Essentials] Using legacy item data provider as mob spawner provider.
[12:44:42] [Server thread/INFO]: [Essentials] Using legacy item data provider as spawn egg provider.
[12:44:42] [Server thread/INFO]: [Essentials] Using legacy potion meta provider as potion meta provider.
[12:44:42] [Server thread/INFO]: Using locale en_US
[12:44:42] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[12:44:42] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[12:44:42] [Server thread/INFO]: [Essentials] Using Vault based permissions (PermissionsEx)
[12:44:42] [Server thread/INFO]: [AutoAnnouncer] Enabling AutoAnnouncer v1.7-03.23
[12:44:42] [Server thread/INFO]: [AutoAnnouncer] Permission support enabled!
[12:44:42] [Server thread/INFO]: [AutoAnnouncer] Settings Loaded (3 announces).
[12:44:42] [Server thread/INFO]: [AutoAnnouncer] Scheduled every 500 seconds!
[12:44:42] [Server thread/INFO]: [AutoAnnouncer] v1.7-03.23 is enabled!
[12:44:42] [Server thread/INFO]: [AutoAnnouncer] Developed by: [Sharkiller]
[12:44:42] [Server thread/INFO]: [Statscraft] Enabling Statscraft v1.2.0
[12:44:42] [Server thread/INFO]: Statscraft enabled
[12:44:42] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.1
[12:44:42] [Server thread/INFO]: [WorldGuard] Loading region data...
[12:44:43] [Server thread/INFO]: [PyrParticles] Enabling PyrParticles v4.0.0
[12:44:43] [Server thread/INFO]: [PyrParticles] INFO: Using config file : pyrparticles_config.yml
[12:44:43] [Server thread/INFO]: [PyrParticles] INFO: Using locale : pyrparticles_en_US.yml
[12:44:43] [Server thread/ERROR]: Error occurred while enabling PyrParticles v4.0.0 (Is it up to date?)
java.lang.NoSuchFieldError: MAGMA
	at be.pyrrh4.pyrparticles.particle.ParticleEffect.<clinit>(ParticleEffect.java:19) ~[?:?]
	at be.pyrrh4.pyrparticles.Commands.<clinit>(Commands.java:23) ~[?:?]
	at be.pyrrh4.pyrparticles.PyrParticles.enable(PyrParticles.java:275) ~[?:?]
	at be.pyrrh4.core.PyrPlugin.onEnable(PyrPlugin.java:191) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[12:44:43] [Server thread/INFO]: [MaintenanceMode] Enabling MaintenanceMode v2.2
[12:44:43] [Server thread/INFO]: ProtocolLib was found! Hooking into MaintenanceMode..
[12:44:43] [Server thread/INFO]: ServerListPlus was found! Overriding methods...
[12:44:43] [Server thread/INFO]: ViaVersion was not found! Not overriding it!
[12:44:43] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:44:43] [Server thread/INFO]: Done (5.707s)! For help, type "help" or "?"
[12:44:43] [Server thread/INFO]: Starting GS4 status listener
[12:44:43] [Query Listener #1/INFO]: Query running on 0.0.0.0:41252
[12:44:43] [Server thread/ERROR]: [FastAsyncWorldEdit] Plugin FastAsyncWorldEdit v18.01.20-ca906cc-986-18.4.1 has failed to register events for class com.boydti.fawe.bukkit.v0.ChunkListener_8 because org/bukkit/event/block/CauldronLevelChangeEvent does not exist.
[12:44:43] [Server thread/INFO]: (FAWE) Plugin 'WorldGuard' found. Using it now.
[12:44:43] [Craft Scheduler Thread - 1/INFO]: [Vault] You are running the latest version
[12:44:44] [Craft Scheduler Thread - 3/INFO]: [PlaceholderAPI] 109 placeholder expansions are available on the cloud.
[12:44:44] [Craft Scheduler Thread - 5/INFO]: [PacketListenerApi] Plugin is up-to-date
[12:44:44] [Craft Scheduler Thread - 5/INFO]: [BuycraftX] Fetching all due players...
[12:44:44] [Craft Scheduler Thread - 6/INFO]: Checking update...
[12:44:44] [Craft Scheduler Thread - 3/INFO]: [PlaceholderAPI] 1 installed expansions have updates available.
[12:44:44] [Craft Scheduler Thread - 6/WARN]: Exception in thread "Craft Scheduler Thread - 6" 
[12:44:44] [Craft Scheduler Thread - 6/WARN]: org.apache.commons.lang.UnhandledException: Plugin eZProtector v4.1.5 generated an exception while executing task 26
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.run(SpigotUpdater.java:102)
	at ez.plugins.dan.SpigotUpdater.SpigotUpdater.<init>(SpigotUpdater.java:80)
	at ez.plugins.dan.SpigotUpdater.UpdateChecker.checkUpdate(UpdateChecker.java:39)
	at ez.plugins.dan.Main$1.run(Main.java:79)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[12:44:45] [Craft Scheduler Thread - 5/INFO]: [BuycraftX] Fetched due players (0 found).

**Comment by PYRRH4** [comment]
Fixed in [PyrParticles v4.1.0](https://www.spigotmc.org/resources/pyrparticles-formerly-pparticles-%E2%97%86-cosmetics-plugin.10225/update?update=219503)
