### ISSUE TITLE
Plugin doesn't work again

### ISSUE THREAD

**Issue by Fyrlex** [PYRRH4/PyrParticles#2]
### Issue description
Another error, how is this plugin supposed to work on 1.7 if you put in 1.8 blocks? (Prismarine)
Try to make sure you don't have 1.8+ blocks in this, otherwise it won't work, last time it was MAGMA now it's PRISMARINE.

### Versions

Spigot : 
1.7.10
PyrCore : 
3.2.11
PyrParticles : 
4.0.1
### Log file
`[23:46:08 ERROR]: Error occurred while enabling PyrParticles v4.0.1 (Is it up to date?)
java.lang.NoSuchFieldError: PRISMARINE
        at be.pyrrh4.pyrparticles.trail.Trail.<clinit>(Trail.java:26) ~[?:?]
        at be.pyrrh4.pyrparticles.Commands.<clinit>(Commands.java:29) ~[?:?]
        at be.pyrrh4.pyrparticles.PyrParticles.enable(PyrParticles.java:275) ~[?:?]
        at be.pyrrh4.core.PyrPlugin.onEnable(PyrPlugin.java:191) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-SNAPSHOT-b1657.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
[23:46:08 INFO]: Server permissions file permissions.yml is empty, ignoring it`

**Comment by PYRRH4** [comment]
Fixed all compat problems in [PyrParticles v4.0.2](https://www.spigotmc.org/resources/10225/update?update=219883), thanks for your patience.
